export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const ADD_TODO_LOADING="ADD_TODO_LOADING"
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE="ADD_TODO_FAILURE"